### PR TITLE
Discovered another value-related bug

### PR DESCRIPTION
**Pull request by sergei-maertens**
Edited through github itself, I hope the tests pass :-)

### CODE REVIEW

**Comment by funkybob** [comment]
Currently the templates use default to deal with None -> "None".

I'm not comfortable with changing None -> '' ... because '' may be a valid value.

**Comment by sergei-maertens** [comment]
I understand. However the current value is set to 'None' instead of None
because of force_text, which is even less correct.

**Comment by sergei-maertens** [comment]
Actually, thinking more about it, the evaluated value must be checked for
None or boolean type I guess, and only force_text if it isn't one of these.
Than the default filter can kick in and operate on the expected type
instead of always on a string.

Tough edge cases.

**Comment by sergei-maertens** [comment]
Closing this in favour for PR #34

**Pull request closed without merging**
